# Generated by Django 4.2.5 on 2023-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
