# Generated by Django 4.2.5 on 2023-09-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=25),
        ),
    ]
